site_name: "Terraform Provider: Harbor"
site_url: https://nolte.github.io/terraform-provider-harbor/
repo_url: https://github.com/nolte/terraform-provider-harbor

nav:
  - Getting Started: index.md
  - Data Sources:
      - harbor_label: data_sources/harbor_label.md
      - harbor_project: data_sources/harbor_project.md
      - harbor_registry: data_sources/harbor_registry.md
  - Resources:
      - harbor_config_system: resources/harbor_config_system.md
      - harbor_configuration: resources/harbor_configuration.md
      - harbor_label: resources/harbor_label.md
      - harbor_project_member: resources/harbor_project_member.md
      - harbor_project: resources/harbor_project.md
      - harbor_registry: resources/harbor_registry.md
      - harbor_replication: resources/harbor_replication.md
      - harbor_retention_policy: resources/harbor_retention_policy.md
      - harbor_robot_account: resources/harbor_robot_account.md
      - harbor_tasks: resources/harbor_tasks.md
      - harbor_usergroup: resources/harbor_usergroup.md
  - Guides:
      - Development: guides/development.md
      - Local E2E Tests: guides/kind.md
theme: readthedocs
markdown_extensions:
  - toc:
      permalink: True
extra_css:
  - css/table.css
extra_javascript:
  # fix for https://github.com/mkdocs/mkdocs/issues/2028
  - js/table.js
