site_name: "Terraform Provider: Harbor"
site_url: https://nolte.github.io/terraform-provider-harbor/
repo_url: https://github.com/nolte/terraform-provider-harbor
docs_dir: documentation/mkdocs
nav:
  - Getting Started: index.md
  - Data Sources:
      - harbor_label: gen/data_sources/harbor_label.md
      - harbor_project: gen/data_sources/harbor_project.md
      - harbor_registry: gen/data_sources/harbor_registry.md
  - Resources:
      - harbor_config_system: gen/resources/harbor_config_system.md
      - harbor_configuration: gen/resources/harbor_configuration.md
      - harbor_label: gen/resources/harbor_label.md
      - harbor_project_member: gen/resources/harbor_project_member.md
      - harbor_project: gen/resources/harbor_project.md
      - harbor_registry: gen/resources/harbor_registry.md
      - harbor_replication: gen/resources/harbor_replication.md
      - harbor_retention_policy: gen/resources/harbor_retention_policy.md
      - harbor_robot_account: gen/resources/harbor_robot_account.md
      - harbor_tasks: gen/resources/harbor_tasks.md
      - harbor_usergroup: gen/resources/harbor_usergroup.md
  - Guides:
      - Development: guides/development.md
      - Local E2E Tests: guides/kind.md
theme: readthedocs
markdown_extensions:
  - toc:
      permalink: True
  - pymdownx.snippets:
      base_path: .
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.highlight
extra_css:
  - css/table.css
  - css/extras.css
extra_javascript:
  # fix for https://github.com/mkdocs/mkdocs/issues/2028
  - js/table.js
